version: '3.8'

services:
  doctor-service-db:
    container_name: doctor-service-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: lib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - internal-net

  doctor-service:
    container_name: doctor-service
    image: doctor-service-image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - doctor-service-db
#      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://doctor-service-db:5432/lib
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8092:8092"
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24228"
        fluentd-async: "true"
        tag: doctor-service
    labels:
      - "prometheus.port=8092"
      - "prometheus.path=/actuator/prometheus"
    networks:
      - internal-net
      - kafka-network
      - prometheus-network
      - logging-net
    volumes:
      - ./../logs:/var/log/app
      - /var/run/docker.sock:/var/run/docker.sock

  fluentd-doctor:
    build:
      context: .
      dockerfile: ./fluentd/Dockerfile
    container_name: fluentd-doctor
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24228:24228"
    networks:
      - logging-net

networks:
  internal-net:
    internal: true
  kafka-network:
    external: true
    name: kafka-network
  prometheus-network:
    external: true
    name: prometheus-network
  logging-net:
    external: true
    name: logging-network
