#spring:
#  datasource:
#    url: jdbc:tc:postgresql:14:///doctor_service_test
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect