name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Create required Docker networks
        run: |
          docker network create prometheus-network || true
          docker network create kafka-network || true
          docker network create logging-network || true

      - name: Start Docker Compose Services
        run: |
          docker compose up -d
          sleep 10 # Ensure services are ready

      - name: Run Tests
        run: mvn test

      - name: Login to Docker Registry
        # Only run on push to main or develop, not on PRs
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          # For Docker Hub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # For GitHub Container Registry, use:
          # registry: ghcr.io
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            andrei839/swa_doctor_service:latest
            andrei839/swa_doctor_service:${{ github.sha }}
          cache-from: type=registry,ref=andrei839/swa_doctor_service:latest
          cache-to: type=inline

      - name: Stop Docker Compose Services
        if: always()
        run: docker compose down